project:
  type: website
  output-dir: docs

website:
  title: "Google Earth Engine Python Interface: Accessing and Analyzing Geospatial Data"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: aboutus.qmd
        text: About Us

format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap
format:
  html:
    theme: default
    css: background.css

execute:
  freeze: auto
